import {test} from 'node:test';import assert from 'node:assert/strict';
import {fresh} from '../src/engine.js';import {notificationPlan,notificationManager} from '../src/notification-plan.js';
const now=new Date(2026,9,6,8,0).getTime();
test('lembretes diurnos por necessidade com intervalo de duas horas por motivo',()=>{const p=fresh('pets-0','Lua',now);p.stats.food=30;const plan=notificationPlan(p,now);assert.ok(plan.length);const days={},last={};for(const n of plan){assert.ok(n.schedule.at>now);assert.ok(n.schedule.at.getHours()>=9&&n.schedule.at.getHours()<21);assert.equal(n.isExactNotification,false);const d=n.schedule.at.toDateString();days[d]=(days[d]||0)+1;for(const code of n.extra.codes){if(last[code])assert.ok(n.schedule.at-last[code]>=2*3600000);last[code]=n.schedule.at;}}assert.equal(new Set(plan.map(n=>n.id)).size,plan.length);});
test('pet morto ou inexistente não recebe lembretes; plano não ultrapassa morte prevista',()=>{assert.deepEqual(notificationPlan(null,now),[]);const p=fresh('pets-0','Lua',now);p.dead=true;assert.deepEqual(notificationPlan(p,now),[]);p.dead=false;p.ill=true;p.illnessHours=119;p.neglectHours=119;p.stats.health=0;p.stats.food=0;assert.deepEqual(notificationPlan(p,now),[]);});
function fixture(display='granted'){const calls=[],data=new Map();let pending=[];const api={getPending:async()=>({notifications:pending}),cancel:async x=>{calls.push(['cancel',x]);pending=pending.filter(n=>!x.notifications.some(c=>c.id===n.id));},checkPermissions:async()=>({display}),requestPermissions:async()=>{calls.push(['permission']);return {display};},createChannel:async()=>{},schedule:async x=>{calls.push(['schedule',x]);pending=x.notifications;}};const storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};return {calls,api,storage};}
test('permissão negada não agenda e não informa ativação',async()=>{const f=fixture('denied'),states=[];const m=notificationManager({...f,platform:'android',onStatus:s=>states.push(s)});await m.toggle(fresh('pets-0','Lua'));assert.equal(m.status(),'disabled');assert.ok(!f.calls.some(c=>c[0]==='schedule'));assert.deepEqual(states,['denied']);});
test('cuidados substituem agenda sem duplicação e desligar cancela',async()=>{const f=fixture(),m=notificationManager({...f,platform:'android'}),p=fresh('pets-0','Lua');await m.toggle(p);const first=f.calls.filter(c=>c[0]==='schedule').at(-1)[1].notifications;assert.ok(first.length);p.stats.food=100;await m.sync(p);assert.ok(f.calls.some(c=>c[0]==='cancel'));await m.toggle(p);assert.equal(m.status(),'disabled');assert.deepEqual((await f.api.getPending()).notifications,[]);});
test('web não tenta plugin nativo; falha de agendamento não anuncia sucesso',async()=>{const f=fixture(),states=[];const web=notificationManager({...f,platform:'web',onStatus:s=>states.push(s)});await web.toggle(fresh('pets-0','Lua'));assert.equal(f.calls.length,0);f.api.schedule=async()=>{throw Error('failed');};const m=notificationManager({...f,platform:'android',onStatus:s=>states.push(s)});await m.toggle(fresh('pets-0','Lua'));assert.deepEqual(states,['web','error']);});
test('último estado vence pedidos simultâneos, incluindo remoção do pet',async()=>{const f=fixture(),m=notificationManager({...f,platform:'android'});await m.toggle(fresh('pets-0','Lua'));await Promise.all([m.sync(fresh('pets-0','Lua')),m.sync(null)]);assert.deepEqual((await f.api.getPending()).notifications,[]);});

test('brincar e cocô têm lembretes próprios; histórico evita repetir aviso ao reabrir',()=>{const p=fresh('pets-0','Lua',now);p.stats.joy=20;p.waste=1;const plan=notificationPlan(p,now);assert.ok(plan[0].extra.codes.includes('joy'));assert.ok(plan[0].extra.codes.includes('waste'));const last={joy:now,waste:now};const next=notificationPlan(p,now,last);for(const n of next.filter(n=>n.extra.codes.includes('joy')||n.extra.codes.includes('waste')))assert.ok(n.schedule.at-now>=2*3600000);});
