import {test} from 'node:test';import assert from 'node:assert/strict';
import {activeSpecies,palettes} from '../src/engine.js';import {petDrawing} from '../src/pets.js';
test('25 pets têm olhos que fecham e uma única expressão, sem dentes soltos',()=>{for(const pet of activeSpecies){for(const palette of palettes[pet.id]||[null]){for(const mode of ['idle','happy','bored','sad','sick','sleep','sleepy']){const svg=petDrawing({...pet,palette},mode);assert.ok(svg.includes('xmlns='),pet.id);assert.equal((svg.match(/class="eyes"/g)||[]).length,1,pet.id);if(!['selva-2','selva-fox','exoticos-penguin','dinos-pterosaur','selva-owl'].includes(pet.id))assert.equal((svg.match(/class="mouth /g)||[]).length,1,pet.id+mode);if(['sleep','sleepy'].includes(mode)){assert.ok(!svg.includes('class="teeth"'),pet.id);const eyes=svg.match(/<g class="eyes">(.*?)<\/g>/s)?.[1];assert.ok(!eyes.includes('<ellipse'),pet.id);assert.ok(eyes.includes('<path'),pet.id);}}}}});
test('barriga do morcego fica atrás da cabeça em todas as expressões',()=>{const s=activeSpecies.find(s=>s.id==='sombrios-1');for(const mode of ['happy','sleep','sad','sick']){const svg=petDrawing(s,mode);assert.ok(svg.indexOf('class="bat-belly"')<svg.indexOf('class="bat-head"'));assert.match(svg,/<ellipse[^>]*cx="100"[^>]*cy="151"[^>]*class="bat-belly"/);}});
import {quadrupedIds} from '../src/pet-standard.js';
test('quadrúpedes acordados têm quatro patas e uma única face; cuidados preservam a pose',()=>{for(const id of quadrupedIds){const pet=activeSpecies.find(s=>s.id===id);for(const palette of palettes[id]||[null]){const svg=petDrawing({...pet,palette,walking:true},'happy');assert.equal((svg.match(/class="pet-leg leg-/g)||[]).length,4,id);assert.equal((svg.match(/class="eyes"/g)||[]).length,1,id);assert.match(svg,/quadruped-pose/,id);assert.ok(!petDrawing({...pet,palette,carePose:true},'sleep').includes('quadruped-pose'),id);}}});

test('ursos mantêm a pose original, mesmo ao passear',()=>{for(const id of ['selva-4','selva-brown','selva-polar','exoticos-penguin']){const pet=activeSpecies.find(s=>s.id===id);assert.ok(!quadrupedIds.includes(id));assert.ok(!petDrawing({...pet,walking:true},'happy').includes('quadruped-pose'));}});

test('raposa e pinguim não têm boca humana em nenhuma pose',()=>{for(const id of ['selva-fox','exoticos-penguin'])for(const carePose of [false,true])for(const mode of ['happy','sleep','sad','sick'])assert.ok(!petDrawing({...activeSpecies.find(s=>s.id===id),carePose},mode).includes('class="mouth '),id+mode);});
