import {chromium} from 'playwright';
import {createServer} from 'vite';
import {mkdir} from 'node:fs/promises';
const server=await createServer({server:{host:'127.0.0.1',port:5186}});await server.listen();
const browser=await chromium.launch({executablePath:'/tmp/petverso-headless/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox','--single-process','--in-process-gpu']});
try{
const page=await browser.newPage({viewport:{width:1080,height:1000}});await page.goto('http://127.0.0.1:5186');
await page.evaluate(async()=>{
const {activeSpecies}=await import('/src/engine.js');const {petDrawing}=await import('/src/pets.js');
const pacifier='<svg viewBox="0 0 64 64"><ellipse cx="32" cy="18" rx="10" ry="14" fill="#ffd8be" stroke="#e3ae89" stroke-width="2"/><path d="M9 27Q32 19 55 27L51 41Q32 49 13 41Z" fill="#9bdeed" stroke="#4bafc7" stroke-width="3"/><circle cx="32" cy="40" r="9" fill="#ffb1d4"/><circle cx="32" cy="49" r="11" fill="none" stroke="#da79ad" stroke-width="5"/></svg>';
function art(id,phase){let s={...activeSpecies.find(x=>x.id===id),carePose:id==='selva-0'||(id==='pets-mouse'&&phase<2)};if(id==='exoticos-penguin')s.palette={color:phase===0?'#b5bfcc':phase===1?'#96aac4':'#7d90b9'};let svg=petDrawing(s,'happy');if(id==='selva-0')svg=svg.replace(/<ellipse[^>]*fill="#b77945"[^>]*\/>/g,x=>phase===0?'':phase===1?x.replace(/rx="22"/,'rx="11"').replace(/ry="22"/,'ry="11"'):x);if(id==='exoticos-penguin')svg=svg.replace('<path d="M89 102','<ellipse cx="100" cy="118" rx="13" ry="13" fill="#fff0d4"/><path d="M89 102');if(id==='selva-fox'&&phase<2){const tip=phase===0?174:182;svg=svg.replace('25 17-26 12',`${tip-165} 17-${tip-164} 12`).replace('M185 102l7 4-7 4-4-5Z',`M${tip-5} 102l7 4-7 4-4-5Z`);}return svg;}
const rows=[['selva-0','León'.replace('ó','o'),'Sans juba|Juba curta|Juba completa'],['exoticos-penguin','Pinguim','Plumagem cinza|Troca de plumagem|Coloração adulta'],['selva-fox','Raposa','Pequena e curiosa|Corpo em crescimento|Focinho e cauda completos'],['pets-mouse','Ratinho','Pequeno|Em crescimento|Quatro patas ao passear']];rows[0][1]='Leão';rows[0][2]='Sem juba|Juba curta|Juba completa';
document.body.innerHTML='<main class="growth-preview"><header><strong>PetVerso</strong><span>PRÉVIA · EVOLUÇÃO</span></header><h1>Crescendo com você</h1><p class="intro">Bebê, jovem e adulto — cada pet com sua identidade.</p><div class="columns"><span></span><b>Bebê</b><b>Jovem</b><b>Adulto</b></div>'+rows.map(([id,name,hints])=>'<section class="pet-row"><h2>'+name+'</h2>'+[0,1,2].map(i=>'<div class="phase"><div class="drawing" style="--size:'+([.66,.83,1][i]*150)+'px">'+art(id,i)+'</div><small>'+hints.split('|')[i]+'</small></div>').join('')+'</section>').join('')+'<footer>Estudo visual · metas e proporções propostas</footer></main>';
document.head.insertAdjacentHTML('beforeend',`<style>body{margin:0;background:#fff2df;color:#354859}.growth-preview{padding:28px 34px;font-family:Nunito,sans-serif}.growth-preview header{display:flex;justify-content:space-between;align-items:center;color:#36869c}.growth-preview header strong{font:32px "Lilita One",sans-serif}.growth-preview header span{font-size:13px;font-weight:800;letter-spacing:2px}.growth-preview h1{font:36px "Lilita One",sans-serif;margin:20px 0 4px}.growth-preview .intro{margin:0 0 20px;color:#7e8b82}.columns,.pet-row{display:grid;grid-template-columns:130px repeat(3,1fr);align-items:center;text-align:center}.columns{margin-bottom:10px;color:#408798}.pet-row{margin-bottom:12px;background:#fffcf4;border:2px solid #efdbc0;border-radius:24px;padding:6px 16px;box-shadow:0 4px #ecd1ad}.pet-row h2{font:24px "Lilita One",sans-serif;text-align:left}.phase{height:174px;display:flex;flex-direction:column;align-items:center;justify-content:end}.drawing{height:146px;width:190px;display:flex;align-items:end;justify-content:center}.drawing svg{width:var(--size);height:var(--size);animation:none!important}.drawing svg *{animation:none!important}.phase small{height:24px;font-size:12px;color:#7d817c}.growth-preview footer{font-size:12px;color:#9d8c77;text-align:center;margin-top:18px}body:after{display:none}</style>`);
});await mkdir('previews',{recursive:true});await page.screenshot({path:'previews/evolucao-pets.png',fullPage:true});
await page.setViewportSize({width:540,height:1000});await page.evaluate(async()=>{
const {colorfulIcon}=await import('/src/icons.js');
const cup='<svg viewBox="0 0 64 64"><ellipse cx="32" cy="18" rx="10" ry="14" fill="#ffd8be"/><path d="M9 27Q32 19 55 27L51 41Q32 49 13 41Z" fill="#9bdeed" stroke="#4bafc7" stroke-width="3"/><circle cx="32" cy="40" r="9" fill="#ffb1d4"/><circle cx="32" cy="49" r="11" fill="none" stroke="#da79ad" stroke-width="5"/></svg>';
const missions=[['sun','Dias juntos',1,2],['bath','Banhos',3,8],['feed','Refeições',7,12],['games','Minijogos',4,6],['brain','Inteligência',9,15]];
document.body.innerHTML='<main class="missions-preview"><header>PetVerso</header><h1>Meu crescimento</h1><button class="growth-card">'+cup+'<div><strong>Bebê</strong><span>Veja o que falta para crescer</span></div><b>›</b></button><div class="modal-example"><button class="close" aria-label="Fechar">×</button>'+cup+'<h2>Bebê</h2><p>Rumo à fase jovem</p><div class="mini-stage"><b class="active">Bebê</b><span>→</span><b>Jovem</b><span>→</span><b>Adulto</b></div>'+missions.map(([icon,name,n,total])=>'<div class="mission"><span class="mission-icon">'+colorfulIcon(icon)+'</span><div><div class="mission-label"><strong>'+name+'</strong><b>'+n+' / '+total+'</b></div><div class="progress"><i style="width:'+n/total*100+'%"></i></div></div></div>').join('')+'<div class="hint">Cada cuidado ajuda seu pet a crescer</div><button class="continue">Continuar cuidando</button></div><small class="preview-note">Prévia · números ilustrativos e metas propostas</small></main>';
document.head.insertAdjacentHTML('beforeend','<style>.missions-preview{padding:30px 24px;font-family:Nunito,sans-serif}.missions-preview header{font:30px "Lilita One";color:#39849b}.missions-preview h1{font:32px "Lilita One";margin:24px 0 16px}.growth-card{display:flex;align-items:center;gap:14px;width:100%;background:#e6faf7;border:3px solid #a8dfdd;border-radius:22px;padding:15px;box-shadow:0 5px #8dcace;text-align:left;color:#354859}.growth-card svg{width:55px;height:55px}.growth-card div{flex:1}.growth-card strong{display:block;font:25px "Lilita One"}.growth-card span{font-size:14px}.growth-card b{font-size:34px}.modal-example{position:relative;background:#fffcf4;border:4px solid white;border-radius:30px;box-shadow:0 8px #e6ceb0;margin-top:28px;padding:22px}.modal-example>svg{display:block;width:65px;height:65px;margin:auto}.modal-example h2{font:34px "Lilita One";text-align:center;margin:9px 0 0}.modal-example>p{text-align:center;margin:4px 0 18px;color:#7e8b82}.close{position:absolute;right:14px;top:10px;background:none;border:0;font-size:28px;color:#607080;box-shadow:none}.mini-stage{display:flex;align-items:center;justify-content:center;gap:10px;font-size:13px;margin-bottom:22px;color:#9ba29a}.mini-stage b{padding:7px 14px;background:#f0ece2;border-radius:16px}.mini-stage .active{background:#fae0ee;color:#b36b99}.mission{display:flex;align-items:center;gap:14px;padding:10px 0}.mission-icon svg{width:36px;height:36px}.mission-icon{font-family:system-ui;font-size:29px;width:44px;text-align:center}.mission>div{flex:1}.mission-label{display:flex;justify-content:space-between;font-size:16px}.mission-label>b{color:#438b97}.progress{height:11px;background:#e8e8ef;border-radius:12px;margin-top:7px;overflow:hidden}.progress i{display:block;height:100%;background:#74cdb8;border-radius:12px}.hint{margin:17px 0;color:#7e8b82;font-size:14px;text-align:center}.continue{width:100%;background:#7bd3d5;color:#285d70;border:2px solid #ade9e6;border-radius:16px;padding:13px;box-shadow:0 4px #5eacb9;font:20px "Lilita One"}.preview-note{display:block;text-align:center;color:#968b80;font-size:11px;margin:19px 0}</style>');
});await page.screenshot({path:'previews/evolucao-missoes.png',fullPage:true});console.log('Prévias de evolução e missões criadas.');
}finally{await browser.close();await server.close();}
