import {chromium} from 'playwright';import {createServer} from 'vite';import {mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const server=await createServer({server:{host:'127.0.0.1',port:5198}});await server.listen();const browser=await chromium.launch({executablePath:'/tmp/petverso-headless/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox','--single-process','--in-process-gpu']});
try{const page=await browser.newPage({viewport:{width:390,height:844}});page.setDefaultTimeout(5000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5198');
async function adopt(id,intelligence=50,sleeping=false){await page.evaluate(async({id,intelligence,sleeping})=>{const {fresh}=await import('/src/engine.js');const p=fresh(id,'Companheiro');p.stats.intelligence=intelligence;p.growth.level=2;p.sleeping=sleeping;localStorage.setItem('petverso-v1',JSON.stringify(p));},{id,intelligence,sleeping});await page.reload();await page.locator('[data-scene="living"]').click();}
await adopt('pets-1',49);assert.equal(await page.locator('.skill-badge').getAttribute('aria-disabled'),'true');await page.locator('.skill-badge').click({force:true});assert.match(await page.locator('.toast').innerText(),/49 \/ 50/);assert.equal(await page.locator('.skills-dialog').count(),0);await page.waitForTimeout(3100);await page.locator('.skill-badge').click({force:true});assert.equal(await page.locator('.toast.show').count(),0);
await adopt('pets-1');await page.locator('.skill-badge').click({force:true});await page.waitForFunction(()=>document.querySelector('.performing-trick'));assert.equal(await page.locator('.world').getAttribute('data-skill-busy'),'true');assert.equal(await page.locator('.call-moving').count(),0);await page.waitForTimeout(3300);assert.equal(await page.locator('.performing-trick').count(),0);assert.ok(Number(await page.locator('.skill-seconds').innerText())>0);await page.locator('[data-scene="garden"]').click();await page.locator('[data-scene="living"]').click();assert.ok(Number(await page.locator('.skill-seconds').innerText())>0);await page.locator('.skill-badge').click({force:true});assert.equal(await page.locator('.performing-trick').count(),0);
await adopt('pets-1',100,true);await page.locator('.skill-badge').click({force:true});assert.equal(await page.locator('.performing-trick').count(),0);assert.deepEqual(errors,[]);
await page.setViewportSize({width:1200,height:1350});await mkdir('previews/trick-gallery-frames',{recursive:true});
await page.evaluate(async()=>{const {activeSpecies}=await import('/src/engine.js');const {petDrawing}=await import('/src/pets.js');const {tricks,animateTrick}=await import('/src/pet-tricks.js');document.body.innerHTML=`<main class="review"><h1>PetVerso · truques da Sala</h1><p>50 de inteligência · 15 segundos de intervalo</p><div class="cards">${activeSpecies.map(s=>`<section class="card"><h2>${s.name}</h2><div class="preview-pet" data-species="${s.id}"><div class="pet-facing"></div></div><p>${tricks[s.id][1]}</p></section>`).join('')}</div></main>`;document.head.insertAdjacentHTML('beforeend',`<style>body{margin:0;background:#fff2df}.review{padding:24px}.review>h1{font:32px "Lilita One";color:#39869b;margin:0}.review>p{margin:8px 0 20px}.cards{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}.card{text-align:center;background:#fffaf0;border:2px solid #eadabd;border-radius:20px;padding:9px;overflow:visible}.card h2{font:17px "Lilita One";margin:0}.card>p{font:13px Nunito;margin:4px 0;min-height:35px}.preview-pet{width:140px;height:180px;position:relative;margin:0 auto}.preview-pet>.pet-facing{width:105px;height:105px;position:absolute;left:18px;top:22px}.preview-pet .creature{width:100%;height:100%;overflow:visible}.preview-pet .trick-effect{z-index:6}body:after{display:none}</style>`);window.replay=()=>{window.cancels?.forEach(fn=>fn());window.cancels=activeSpecies.map(s=>{const id=s.id,walking=true;return animateTrick(document.querySelector(`[data-species="${id}"]`),id,{draw:()=>petDrawing({...s,growthLevel:2,carePose:!walking},'happy')});});};window.replay();});
for(let i=0;i<32;i++){await page.screenshot({path:`previews/trick-gallery-frames/${String(i).padStart(3,'0')}.png`});await page.waitForTimeout(70);}await page.evaluate(()=>window.replay());await page.waitForTimeout(1000);await page.screenshot({path:'previews/truques-sala-todas-especies.png',fullPage:true});assert.deepEqual(errors,[]);console.log('22 truques, bloqueio discreto, cooldown persistente, sono e exclusão de caminhada conferidos.');}finally{await browser.close();await server.close();}
