export const CALL_INTELLIGENCE=25;
export function canCallPet(p,scene){return !!p&&!p.dead&&!p.sleeping&&scene!=='bathroom'&&p.stats.intelligence>=CALL_INTELLIGENCE;}
const inside=(p,r)=>p.x>=r.left&&p.x<=r.right&&p.y>=r.top&&p.y<=r.bottom;
export function planWalk(start,end,bounds,obstacles=[]){
 const free=p=>p.x>=bounds.left&&p.x<=bounds.right&&p.y>=bounds.top&&p.y<=bounds.bottom&&!obstacles.some(r=>inside(p,r));
 const clear=(a,b)=>{const n=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/4));for(let i=1;i<=n;i++)if(!free({x:a.x+(b.x-a.x)*i/n,y:a.y+(b.y-a.y)*i/n}))return false;return true;};
 if(!free(end))return null;if(clear(start,end))return [start,end];
 // Visibility graph around obstacle corners, with a small margin for the feet.
 const points=[start,end];for(const r of obstacles)for(const p of [{x:r.left-2,y:r.top-2},{x:r.right+2,y:r.top-2},{x:r.left-2,y:r.bottom+2},{x:r.right+2,y:r.bottom+2}])if(free(p))points.push(p);
 const distance=points.map(()=>Infinity),prev=points.map(()=>-1),visited=new Set();distance[0]=0;
 for(let k=0;k<points.length;k++){let u=-1;for(let i=0;i<points.length;i++)if(!visited.has(i)&&(u<0||distance[i]<distance[u]))u=i;if(u<0||!Number.isFinite(distance[u]))break;if(u===1)break;visited.add(u);for(let v=1;v<points.length;v++)if(v!==u&&!visited.has(v)&&clear(points[u],points[v])){const d=distance[u]+Math.hypot(points[u].x-points[v].x,points[u].y-points[v].y);if(d<distance[v]){distance[v]=d;prev[v]=u;}}}
 if(!Number.isFinite(distance[1]))return null;const route=[];for(let i=1;i!==-1;i=prev[i])route.unshift(points[i]);return route[0]===start?route:null;
}
export function bindCallPet({world,target,getPet,scene,drawWalking,onLocked,onBlocked,reducedMotion}){
 if(!world||!target||scene==='bathroom')return ()=>{};
 let down=null,frame=0,timer=0,disposed=false,moving=false,controlled=false,position=null,busy=false;
 const face=target.querySelector('.pet-facing');
 function geometry(){const w=world.getBoundingClientRect(),r=target.getBoundingClientRect(),floor=world.querySelector('.floor')?.getBoundingClientRect();const margin=r.width*.36;
 const bounds={left:margin+8,right:w.width-margin-8,top:Math.max((floor?floor.top-w.top:w.height*.64)+12,90),bottom:w.height-40};
 const obstacles=[...world.querySelectorAll('.room-furniture,.garden-item,.bed,.bedside-dresser,.park-object')].map(el=>{const b=el.getBoundingClientRect();return {left:b.left-w.left-margin,right:b.right-w.left+margin,top:b.top-w.top+b.height*.5-7,bottom:b.bottom-w.top+7};});
 const raw=position||{x:r.left-w.left+r.width/2,y:r.bottom-w.top-r.height*.065};const p={x:Math.max(bounds.left,Math.min(bounds.right,raw.x)),y:Math.max(bounds.top,Math.min(bounds.bottom,raw.y))};return {w,r,bounds,obstacles,p};}
 function place(p){const {w,r}=geometry();position=p;target.style.setProperty('left',(p.x-world.clientLeft)+'px','important');target.style.setProperty('bottom',(w.height-world.clientTop-p.y-r.height*.065)+'px','important');}
 function lock(){if(controlled)return;const g=geometry();controlled=true;target.classList.remove('roaming');target.classList.add('call-controlled');target.style.setProperty('transform','translateX(-50%)','important');target.style.setProperty('animation','none','important');face.style.setProperty('animation','none','important');place(g.p);face.innerHTML=drawWalking();}
 function marker(p){world.querySelector('.call-marker')?.remove();const node=document.createElement('span');node.className='call-marker';node.setAttribute('aria-hidden','true');node.style.left=(p.x-world.clientLeft)+'px';node.style.top=p.y+'px';world.append(node);setTimeout(()=>node.remove(),1600);}
 function walk(route,called=false){cancelAnimationFrame(frame);clearTimeout(timer);lock();moving=true;target.classList.remove('called-idle');target.classList.add('call-moving');world.dataset.petMoving='true';if(called)marker(route.at(-1));let segment=1,startTime=0,from=route[0];
 const finish=()=>{moving=false;target.classList.remove('call-moving');target.classList.add('called-idle');world.dataset.petMoving='false';timer=setTimeout(wander,3500);};
 function animate(t){if(disposed)return;const to=route[segment],dx=to.x-from.x,dy=to.y-from.y;target.dataset.walkDirection=dx<0?'left':'right';if(!target.classList.contains('directional-pet'))face.style.setProperty('transform',`scaleX(${dx<0?-1:1})`,'important');const duration=reducedMotion()?0:Math.hypot(dx,dy)/85*1000;if(!startTime)startTime=t;const ratio=duration?Math.min(1,(t-startTime)/duration):1;place({x:from.x+dx*ratio,y:from.y+dy*ratio});if(ratio===1){if(++segment===route.length){finish();return;}from=to;startTime=t;}frame=requestAnimationFrame(animate);}
 frame=requestAnimationFrame(animate);}
 function wander(){if(busy||disposed||!getPet()||getPet().sleeping||getPet().dead||document.hidden)return;const g=geometry();for(let i=0;i<12;i++){const p={x:g.bounds.left+Math.random()*(g.bounds.right-g.bounds.left),y:g.bounds.top+Math.random()*(g.bounds.bottom-g.bounds.top)};const route=planWalk(g.p,p,g.bounds,g.obstacles);if(route&&Math.hypot(p.x-g.p.x,p.y-g.p.y)>20){walk(route);return;}}timer=setTimeout(wander,3500);}
 function pointerdown(e){if(e.button!==0||e.target.closest('button,#touch-pet,.room-caption'))return;down={x:e.clientX,y:e.clientY,id:e.pointerId};}
 function pointerup(e){if(busy||!down||down.id!==e.pointerId)return;const delta=Math.hypot(e.clientX-down.x,e.clientY-down.y);down=null;if(delta>12)return;const pet=getPet();if(!pet||pet.sleeping||pet.dead)return;const g=geometry(),p={x:e.clientX-g.w.left,y:e.clientY-g.w.top};if(p.y<g.bounds.top||p.y>g.bounds.bottom)return;if(pet.stats.intelligence<CALL_INTELLIGENCE){onLocked();return;}const route=planWalk(g.p,p,g.bounds,g.obstacles);if(!route){onBlocked();return;}walk(route,true);}
 function visibility(){if(document.hidden){cancelAnimationFrame(frame);clearTimeout(timer);moving=false;target.classList.remove('call-moving');target.classList.add('called-idle');}else if(controlled)timer=setTimeout(wander,1000);}
 function pause(){busy=true;cancelAnimationFrame(frame);clearTimeout(timer);lock();target.classList.remove('call-moving','called-idle');world.dataset.petMoving='false';}function resume(){busy=false;face.innerHTML=drawWalking();target.classList.add('called-idle');timer=setTimeout(wander,3500);}world.addEventListener('pet-thought-start',pause);world.addEventListener('pet-thought-end',resume);world.addEventListener('pet-skill-start',pause);world.addEventListener('pet-skill-end',resume);const cancel=()=>{down=null;};world.addEventListener('pointercancel',cancel);world.addEventListener('pointerdown',pointerdown);world.addEventListener('pointerup',pointerup);document.addEventListener('visibilitychange',visibility);
 if(target.classList.contains('call-controlled')){lock();target.classList.add('called-idle');timer=setTimeout(wander,3500);}
 return ()=>{disposed=true;world.removeEventListener('pet-thought-start',pause);world.removeEventListener('pet-thought-end',resume);world.removeEventListener('pet-skill-start',pause);world.removeEventListener('pet-skill-end',resume);cancelAnimationFrame(frame);clearTimeout(timer);world.querySelector('.call-marker')?.remove();world.removeEventListener('pointercancel',cancel);world.removeEventListener('pointerdown',pointerdown);world.removeEventListener('pointerup',pointerup);document.removeEventListener('visibilitychange',visibility);};
}
