const words=['GATO','PATO','BOLA','CASA','LUA','SOL','SAPO','URSO','RATO','OVO','PERA','UVA','CAMA','LEAO','FOCA','PANDA','BANHO','MANGA','COELHO','MACACO','BANANA','AMIGO','PARQUE','CAVALO'];
export function flightDifficulty(seconds){const level=1+Math.floor(Math.max(0,seconds)/30);return {level,speed:Math.min(205,105+(level-1)*13),opening:Math.max(128,190-(level-1)*9),interval:Math.max(1.7,2.7-(level-1)*.12)};}
export function makeWordBoard(round=0,rng=Math.random){const size=Math.min(9,6+Math.floor(round/2)),count=Math.min(6,3+Math.floor(round/2));const grid=Array.from({length:size},()=>Array(size).fill(''));const pool=words.filter(w=>w.length<=size).map(w=>({w,n:rng()})).sort((a,b)=>a.n-b.n).map(x=>x.w);const placed=[];const dirs=round>=2?[[0,1],[1,0],[1,1]]:[[0,1],[1,0]];
 for(const word of pool){if(placed.length>=count)break;const candidates=[];for(let r=0;r<size;r++)for(let c=0;c<size;c++)for(const [dr,dc] of dirs){const cells=Array.from(word,(_,i)=>[r+dr*i,c+dc*i]);if(cells.every(([y,x],i)=>y<size&&x<size&&(!grid[y][x]||grid[y][x]===word[i])))candidates.push(cells);}if(!candidates.length)continue;const cells=candidates[Math.min(candidates.length-1,Math.floor(rng()*candidates.length))];cells.forEach(([r,c],i)=>grid[r][c]=word[i]);placed.push({word,cells});}
 const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';for(const row of grid)for(let c=0;c<size;c++)if(!row[c])row[c]=letters[Math.min(25,Math.floor(rng()*26))];return {size,grid,words:placed};}
export function lineCells(start,end){const dr=end[0]-start[0],dc=end[1]-start[1];if(dr&&dc&&Math.abs(dr)!==Math.abs(dc))return [];const count=Math.max(Math.abs(dr),Math.abs(dc));return Array.from({length:count+1},(_,i)=>[start[0]+Math.sign(dr)*i,start[1]+Math.sign(dc)*i]);}
export function wordFromCells(board,cells){return cells.map(([r,c])=>board.grid[r]?.[c]||'').join('');}
export function wordSearch(area,{onScore,sound}){let round=0,score=0,board,found=new Set(),start=null,drag=false,selection=[],timer=0,stopped=false;const colors=['#e89ac6','#70c8da','#c2a0ea','#e9bd60','#91c674','#ed9b73'];
 function render(){board=makeWordBoard(round);found=new Set();start=null;selection=[];area.innerHTML=`<p class="word-score">${score} pontos · Fase ${round+1}</p><p class="word-help">Arraste sobre as letras ou toque no começo e no fim.</p><div class="word-list">${board.words.map(({word},i)=>`<span data-word="${word}" style="--word-color:${colors[i]}">${word}</span>`).join('')}</div><div class="word-board" style="--word-size:${board.size}" role="group" aria-label="Letras do caça-palavras">${board.grid.flatMap((row,r)=>row.map((letter,c)=>`<button data-letter="${r},${c}" aria-label="${letter}, linha ${r+1}, coluna ${c+1}">${letter}</button>`)).join('')}</div><p class="word-status" role="status">Encontre ${board.words.length} palavras!</p>`;
 const grid=area.querySelector('.word-board');const coord=b=>b.dataset.letter.split(',').map(Number);grid.onpointerdown=e=>{const b=e.target.closest('[data-letter]');if(!b)return;e.preventDefault();if(start){select(coord(b));check();return;}start=coord(b);drag=false;select(start);};grid.onpointermove=e=>{if(!start||!e.buttons)return;const b=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-letter]');if(b&&grid.contains(b)){const end=coord(b);if(end.join()!==start.join())drag=true;select(end);}};grid.onpointerup=()=>{if(drag)check();};grid.onpointercancel=()=>{start=null;selection=[];paint();};grid.onkeydown=e=>{if(!['Enter',' '].includes(e.key))return;const b=e.target.closest('[data-letter]');if(!b)return;e.preventDefault();if(start){select(coord(b));check();}else{start=coord(b);select(start);}};
 }
 function paint(){area.querySelectorAll('[data-letter]').forEach(b=>b.classList.toggle('selecting',selection.some(x=>x.join()===b.dataset.letter)));}
 function select(end){selection=lineCells(start,end);paint();}
 function check(){const text=wordFromCells(board,selection);const match=board.words.find(({word})=>!found.has(word)&&(word===text||word===text.split('').reverse().join('')));if(match){found.add(match.word);score+=20;onScore(score);sound('match');const color=colors[board.words.indexOf(match)];selection.forEach(([r,c])=>{const b=area.querySelector(`[data-letter="${r},${c}"]`);b.classList.add('word-found');b.style.setProperty('--found-color',color);});area.querySelector(`[data-word="${match.word}"]`).classList.add('found');area.querySelector('.word-score').textContent=`${score} pontos · Fase ${round+1}`;area.querySelector('.word-status').textContent=found.size===board.words.length?'Muito bem! Próxima fase…':`${found.size} de ${board.words.length} palavras`;if(found.size===board.words.length){round++;timer=setTimeout(()=>{if(!stopped)render();},900);}}else sound('wrong');start=null;selection=[];paint();}
 render();return ()=>{stopped=true;clearTimeout(timer);};}
export function flight(area,{spriteSvg,onScore,onEnd,sound}){area.innerHTML='<p class="flight-score">0 pontos · Fase 1</p><div class="flight-field"><canvas aria-label="Voo do pet: toque para voar" tabindex="0"></canvas><button class="flight-start">Toque para voar!</button></div><p class="flight-help">Toque ou aperte espaço para subir. Passe entre os troncos!</p>';const canvas=area.querySelector('canvas'),ctx=canvas.getContext('2d'),status=area.querySelector('.flight-score'),startButton=area.querySelector('.flight-start');const W=360,H=480;canvas.width=W*2;canvas.height=H*2;ctx.scale(2,2);const sprite=new Image();sprite.src='data:image/svg+xml,'+encodeURIComponent(spriteSvg.replace(/<svg(?![^>]*xmlns=)/,'<svg xmlns="http://www.w3.org/2000/svg"'));let y=H*.45,v=0,time=0,spawn=0,points=0,started=false,stopped=false,pipes=[],raf=0,last=performance.now();
 function flap(){if(stopped)return;if(!started){started=true;startButton.remove();spawn=1;}v=-220;sound('tap');}
 canvas.onpointerdown=e=>{e.preventDefault();flap();};startButton.onclick=()=>{flap();canvas.focus();};const key=e=>{if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();flap();}};canvas.addEventListener('keydown',key);
 function trunk(x,top,bottom){ctx.fillStyle='#b47849';ctx.strokeStyle='#825338';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(x,top,48,bottom-top,8);ctx.fill();ctx.stroke();ctx.strokeStyle='#dfa66d';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x+15,top+9);ctx.lineTo(x+15,bottom-9);ctx.stroke();ctx.fillStyle='#79bc6d';ctx.beginPath();ctx.roundRect(x-6,top===0?bottom-18:top,60,18,8);ctx.fill();}
 function draw(){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#77d4f1');sky.addColorStop(1,'#dbf7e7');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffe399';ctx.beginPath();ctx.arc(280,65,27,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffffffbb';for(const [x,z]of[[50,90],[210,150]]){ctx.beginPath();ctx.ellipse(x,z,37,13,0,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#a9d687';ctx.beginPath();ctx.moveTo(0,H-35);ctx.quadraticCurveTo(100,H-130,230,H-35);ctx.quadraticCurveTo(310,H-90,W,H-40);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();for(const p of pipes){trunk(p.x,0,p.center-p.opening/2);trunk(p.x,p.center+p.opening/2,H-24);}ctx.fillStyle='#75b879';ctx.fillRect(0,H-24,W,24);ctx.save();ctx.translate(83,y);ctx.rotate(Math.max(-.35,Math.min(.55,v/600)));if(sprite.complete&&sprite.naturalWidth)ctx.drawImage(sprite,-32,-32,64,64);else{ctx.fillStyle='#b499df';ctx.beginPath();ctx.arc(0,0,22,0,Math.PI*2);ctx.fill();}ctx.restore();}
 function end(){stopped=true;cancelAnimationFrame(raf);sound('wrong');onEnd(points);}
 function loop(now){if(stopped)return;const dt=document.hidden?0:Math.min(.035,(now-last)/1000);last=now;if(started&&dt){time+=dt;v+=650*dt;y+=v*dt;const d=flightDifficulty(time);spawn-=dt;if(spawn<=0){pipes.push({x:W+10,center:130+Math.random()*180,opening:d.opening,passed:false});spawn=d.interval;}for(const p of pipes){p.x-=d.speed*dt;if(!p.passed&&p.x+48<65){p.passed=true;points+=10;onScore(points);sound('match');}if(p.x<101&&p.x+48>65&&(y-17<p.center-p.opening/2||y+17>p.center+p.opening/2)){draw();end();return;}}pipes=pipes.filter(p=>p.x>-60);status.textContent=`${points} pontos · Fase ${d.level}`;if(y<17||y>H-41){draw();end();return;}}draw();raf=requestAnimationFrame(loop);}
 raf=requestAnimationFrame(loop);return ()=>{stopped=true;cancelAnimationFrame(raf);canvas.removeEventListener('keydown',key);};}
