const words=['GATO','PATO','BOLA','CASA','LUA','SOL','SAPO','URSO','RATO','OVO','PERA','UVA','CAMA','LEAO','FOCA','PANDA','BANHO','MANGA','COELHO','MACACO','BANANA','AMIGO','PARQUE','CAVALO','RAPOSA','TIGRE','LOBO','ZEBRA','GIRAFA','ELEFANTE','GOLFINHO','CORUJA','TUCANO','ARARA','MORCEGO','DRAGAO','DINO','TARTARUGA','CAMALEAO','AXOLOTE','CAPIVARA','PINGUIM','PEIXE','BORBOLETA','ABELHA','FORMIGA','FLOR','ARVORE','FOLHA','BAMBU','JARDIM','FLORESTA','LAGO','PRAIA','NEVE','CHUVA','NUVEM','ESTRELA','LUZ','AGUA','FRUTA','MACA','MELANCIA','LARANJA','MORANGO','ABACAXI','LIMAO','KIWI','COCO','CENOURA','MILHO','PIPOCA','PETISCO','CARINHO','ABRACO','FELIZ','SORRISO','BRINCAR','CORRER','PULAR','VOAR','DORMIR','LIMPAR','SABAO','TOALHA','ESCOVA','TAPETE','SOFA','VASO','LIVRO','CASINHA','BRINQUEDO','PARQUINHO','QUINTAL','AVENTURA','AMIZADE','PASSEIO','TESOURO','MOEDA','PATINHA','FOFINHO'];
export function flightDifficulty(seconds){const level=1+Math.floor(Math.max(0,seconds)/30);return {level,speed:Math.min(205,105+(level-1)*13),opening:Math.max(128,190-(level-1)*9),interval:Math.max(1.7,2.7-(level-1)*.12)};}
export function makeWordBoard(round=0,rng=Math.random){const size=Math.min(9,6+Math.floor(round/2)),count=Math.min(6,3+Math.floor(round/2));const grid=Array.from({length:size},()=>Array(size).fill(''));const pool=words.filter(w=>w.length<=size).map(w=>({w,n:rng()})).sort((a,b)=>a.n-b.n).map(x=>x.w);const placed=[];const dirs=round>=2?[[0,1],[1,0],[1,1]]:[[0,1],[1,0]];
 for(const word of pool){if(placed.length>=count)break;const candidates=[];for(let r=0;r<size;r++)for(let c=0;c<size;c++)for(const [dr,dc] of dirs){const cells=Array.from(word,(_,i)=>[r+dr*i,c+dc*i]);if(cells.every(([y,x],i)=>y<size&&x<size&&(!grid[y][x]||grid[y][x]===word[i])))candidates.push(cells);}if(!candidates.length)continue;const cells=candidates[Math.min(candidates.length-1,Math.floor(rng()*candidates.length))];cells.forEach(([r,c],i)=>grid[r][c]=word[i]);placed.push({word,cells});}
 const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';for(const row of grid)for(let c=0;c<size;c++)if(!row[c])row[c]=letters[Math.min(25,Math.floor(rng()*26))];return {size,grid,words:placed};}
export function lineCells(start,end){const dr=end[0]-start[0],dc=end[1]-start[1];if(dr&&dc&&Math.abs(dr)!==Math.abs(dc))return [];const count=Math.max(Math.abs(dr),Math.abs(dc));return Array.from({length:count+1},(_,i)=>[start[0]+Math.sign(dr)*i,start[1]+Math.sign(dc)*i]);}
export function wordFromCells(board,cells){return cells.map(([r,c])=>board.grid[r]?.[c]||'').join('');}
export function wordSearch(area,{onScore,sound}){let round=0,score=0,board,found=new Set(),start=null,drag=false,selection=[],timer=0,stopped=false;const colors=['#e89ac6','#70c8da','#c2a0ea','#e9bd60','#91c674','#ed9b73'];
 function render(){board=makeWordBoard(round);found=new Set();start=null;selection=[];area.innerHTML=`<p class="word-score">${score} pontos · Fase ${round+1}</p><div class="word-list">${board.words.map(({word},i)=>`<span data-word="${word}" style="--word-color:${colors[i]}">${word}</span>`).join('')}</div><div class="word-board" style="--word-size:${board.size}" role="group" aria-label="Letras do caça-palavras">${board.grid.flatMap((row,r)=>row.map((letter,c)=>`<button data-letter="${r},${c}" aria-label="${letter}, linha ${r+1}, coluna ${c+1}">${letter}</button>`)).join('')}</div><p class="word-status" role="status">Encontre ${board.words.length} palavras!</p>`;
 const grid=area.querySelector('.word-board');const coord=b=>b.dataset.letter.split(',').map(Number);grid.onpointerdown=e=>{const b=e.target.closest('[data-letter]');if(!b)return;e.preventDefault();if(start){select(coord(b));check();return;}start=coord(b);drag=false;select(start);};grid.onpointermove=e=>{if(!start||!e.buttons)return;const b=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-letter]');if(b&&grid.contains(b)){const end=coord(b);if(end.join()!==start.join())drag=true;select(end);}};grid.onpointerup=()=>{if(drag)check();};grid.onpointercancel=()=>{start=null;selection=[];paint();};grid.onkeydown=e=>{if(!['Enter',' '].includes(e.key))return;const b=e.target.closest('[data-letter]');if(!b)return;e.preventDefault();if(start){select(coord(b));check();}else{start=coord(b);select(start);}};
 }
 function paint(){area.querySelectorAll('[data-letter]').forEach(b=>b.classList.toggle('selecting',selection.some(x=>x.join()===b.dataset.letter)));}
 function select(end){selection=lineCells(start,end);paint();}
 function check(){const text=wordFromCells(board,selection);const match=board.words.find(({word})=>!found.has(word)&&(word===text||word===text.split('').reverse().join('')));if(match){found.add(match.word);score+=20;onScore(score);sound('match');const color=colors[board.words.indexOf(match)];selection.forEach(([r,c])=>{const b=area.querySelector(`[data-letter="${r},${c}"]`);b.classList.add('word-found');b.style.setProperty('--found-color',color);});area.querySelector(`[data-word="${match.word}"]`).classList.add('found');area.querySelector('.word-score').textContent=`${score} pontos · Fase ${round+1}`;area.querySelector('.word-status').textContent=found.size===board.words.length?'Muito bem! Próxima fase…':`${found.size} de ${board.words.length} palavras`;if(found.size===board.words.length){round++;timer=setTimeout(()=>{if(!stopped)render();},900);}}else sound('wrong');start=null;selection=[];paint();}
 render();return ()=>{stopped=true;clearTimeout(timer);};}
export function flight(area,{spriteSvg,onScore,onEnd,sound}){area.innerHTML='<p class="flight-score">0 pontos · Fase 1</p><p class="flight-help">Toque para ganhar altura e atravesse os portais da floresta.</p><div class="flight-field"><canvas aria-label="Voo do pet: toque para voar" tabindex="0"></canvas><button class="flight-start">Toque para começar!</button></div>';const canvas=area.querySelector('canvas'),ctx=canvas.getContext('2d'),status=area.querySelector('.flight-score'),startButton=area.querySelector('.flight-start');const W=360,H=480,DPR=Math.min(2,window.devicePixelRatio||1);canvas.width=W*DPR;canvas.height=H*DPR;ctx.scale(DPR,DPR);const sprite=new Image();sprite.src='data:image/svg+xml,'+encodeURIComponent(spriteSvg.replace(/<svg(?![^>]*xmlns=)/,'<svg xmlns="http://www.w3.org/2000/svg"'));let y=H*.44,v=0,time=0,spawn=0,points=0,started=false,stopped=false,pipes=[],particles=[],raf=0,last=performance.now(),wing=0;
 function flap(){if(stopped)return;if(!started){started=true;startButton.remove();spawn=1.25;}v=Math.max(-265,v-185);wing=.16;for(let i=0;i<4;i++)particles.push({x:59-Math.random()*12,y:y+10+(Math.random()-.5)*16,vx:-35-Math.random()*35,vy:(Math.random()-.5)*35,life:.45});sound('tap');}
 canvas.onpointerdown=e=>{e.preventDefault();flap();};startButton.onclick=()=>{flap();canvas.focus();};const key=e=>{if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();flap();}};canvas.addEventListener('keydown',key);
 function cloud(x,y,scale=1,alpha=.72){ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle='#fffdf8';ctx.beginPath();ctx.ellipse(x,y,32*scale,12*scale,0,0,Math.PI*2);ctx.ellipse(x-20*scale,y+2*scale,20*scale,10*scale,0,0,Math.PI*2);ctx.ellipse(x+22*scale,y+3*scale,23*scale,9*scale,0,0,Math.PI*2);ctx.fill();ctx.restore();}
 function portal(x,top,bottom){ctx.save();ctx.shadowColor='#5a6b4930';ctx.shadowBlur=5;ctx.fillStyle='#9b6a4b';ctx.strokeStyle='#76503b';ctx.lineWidth=3;for(const [a,b] of [[0,top],[bottom,H-22]]){ctx.beginPath();ctx.roundRect(x,a,48,b-a,10);ctx.fill();ctx.stroke();ctx.strokeStyle='#d7a273';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x+14,a+8);ctx.lineTo(x+14,b-8);ctx.stroke();ctx.strokeStyle='#76503b';ctx.lineWidth=3;}ctx.shadowColor='transparent';const crown=(cy,flip)=>{ctx.fillStyle='#70ad78';for(const dx of [-12,8,28,48]){ctx.beginPath();ctx.arc(x+dx,cy+(Math.abs(dx-18)%3)*3,18,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#f6b4c8';for(const dx of [2,31]){ctx.beginPath();ctx.arc(x+dx,cy+(flip?5:-5),4,0,Math.PI*2);ctx.fill();}};crown(top?top:12,1);crown(bottom,0);ctx.restore();}
 function star(s){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(time*1.8);ctx.fillStyle='#ffd86f';ctx.strokeStyle='#fff4bd';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<10;i++){const r=i%2?5:11,a=-Math.PI/2+i*Math.PI/5;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r);}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}
 function background(){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#9dddf3');sky.addColorStop(.65,'#dff2e9');sky.addColorStop(1,'#fff0cd');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffe6a1';ctx.beginPath();ctx.arc(292,64,30,0,Math.PI*2);ctx.fill();cloud(((70-time*10)%500+500)%500-60,92,.9);cloud(((260-time*16)%560+560)%560-70,162,.7,.58);
  ctx.fillStyle='#bad8c2';for(let i=-1;i<5;i++){const x=i*120-(time*13)%120;ctx.beginPath();ctx.moveTo(x,H-32);ctx.quadraticCurveTo(x+62,H-170,x+130,H-32);ctx.fill();}
  ctx.fillStyle='#91c49d';for(let i=-1;i<7;i++){const x=i*82-(time*25)%82;ctx.beginPath();ctx.arc(x,H-25,65,Math.PI,0);ctx.fill();}
  ctx.fillStyle='#74b17d';ctx.fillRect(0,H-23,W,23);for(let i=-1;i<11;i++){const x=i*42-(time*55)%42;ctx.fillStyle=i%2?'#f5acc2':'#fff0a7';ctx.beginPath();ctx.arc(x,H-27-(i%3)*4,3,0,Math.PI*2);ctx.fill();}}
 function draw(){background();for(const p of pipes){portal(p.x,p.center-p.opening/2,p.center+p.opening/2);if(!p.starTaken)star({x:p.x+24,y:p.center});}for(const p of particles){ctx.save();ctx.globalAlpha=Math.max(0,p.life/.45);ctx.fillStyle='#fff6d0';ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);ctx.fill();ctx.restore();}
  ctx.save();ctx.globalAlpha=.18;ctx.fillStyle='#506450';ctx.beginPath();ctx.ellipse(83,H-27,26,6,0,0,Math.PI*2);ctx.fill();ctx.restore();
  ctx.save();ctx.translate(83,y);ctx.rotate(Math.max(-.34,Math.min(.46,v/520)));const bob=!started?Math.sin(performance.now()/320)*3:0;if(sprite.complete&&sprite.naturalWidth)ctx.drawImage(sprite,-34,-34+bob,68,68);else{ctx.fillStyle='#b499df';ctx.beginPath();ctx.arc(0,bob,22,0,Math.PI*2);ctx.fill();}ctx.restore();}
 function end(){stopped=true;cancelAnimationFrame(raf);sound('wrong');onEnd(points);}
 function loop(now){if(stopped)return;const dt=document.hidden?0:Math.min(.032,(now-last)/1000);last=now;if(started&&dt){time+=dt;wing=Math.max(0,wing-dt);v+=610*dt;y+=v*dt;const d=flightDifficulty(time);spawn-=dt;if(spawn<=0){const margin=72+d.opening/2,center=margin+Math.random()*(H-44-margin*2);pipes.push({x:W+15,center,opening:d.opening,passed:false,starTaken:false});spawn=d.interval;}for(const p of pipes){p.x-=d.speed*dt;if(!p.starTaken&&Math.hypot((p.x+24)-83,p.center-y)<24){p.starTaken=true;points+=2;onScore(points);sound('feed');}if(!p.passed&&p.x+48<65){p.passed=true;points+=5;onScore(points);sound('match');}if(p.x<101&&p.x+48>65&&(y-16<p.center-p.opening/2||y+16>p.center+p.opening/2)){draw();end();return;}}pipes=pipes.filter(p=>p.x>-60);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;}particles=particles.filter(p=>p.life>0);status.textContent=`${points} pontos · Fase ${d.level}`;if(y<16||y>H-40){draw();end();return;}}draw();raf=requestAnimationFrame(loop);}
 raf=requestAnimationFrame(loop);return ()=>{stopped=true;cancelAnimationFrame(raf);canvas.removeEventListener('keydown',key);};}
