import {growthProgress,growthNames} from './growth.js';
import {colorfulIcon} from './icons.js';
const baby='<svg class="icon" viewBox="0 0 64 64" aria-hidden="true"><ellipse cx="32" cy="18" rx="10" ry="14" fill="#ffd8be"/><path d="M9 27Q32 19 55 27L51 41Q32 49 13 41Z" fill="#9bdeed" stroke="#4bafc7" stroke-width="3"/><circle cx="32" cy="40" r="9" fill="#ffb1d4"/><circle cx="32" cy="49" r="11" fill="none" stroke="#da79ad" stroke-width="5"/></svg>';

const labels={days:['sun','Dias juntos'],baths:['bath','Banhos'],meals:['feed','Refeições'],games:['games','Minijogos'],intelligence:['brain','Inteligência']};
const symbol=level=>level===0?baby:`<span class="growth-paw growth-paw-${level}">${colorfulIcon('paw')}</span>`;
export function growthCard(p){const g=growthProgress(p);return `<button id="open-growth" class="growth-age phase-${g.level}" aria-label="Ver progresso de crescimento: ${g.name}" title="${g.name}">${symbol(g.level)}<span>${g.name}</span></button>`;}
export function openGrowth(p,onClose){
 const progress=growthProgress(p),el=document.createElement('div');el.className='overlay growth-overlay';
 el.innerHTML=`<section class="dialog growth-dialog" role="dialog" aria-modal="true" aria-labelledby="growth-title"><button class="close" aria-label="Fechar">×</button><div class="growth-symbol">${symbol(progress.level)}</div><h2 id="growth-title">${progress.name}</h2><p>${progress.next?'Rumo à fase '+progress.next.toLowerCase():'Todas as fases concluídas!'}</p><div class="growth-phases">${growthNames.map((name,i)=>`<b class="${i===progress.level?'current':i<progress.level?'complete':''}">${name}</b>`).join('<span aria-hidden="true">→</span>')}</div>${progress.missions.map(({key,value,goal,done})=>`<div class="growth-mission">${colorfulIcon(labels[key][0])}<div><div class="growth-label"><strong>${labels[key][1]}</strong><b>${done?'✓ ':''}${Math.floor(value)} / ${goal}</b></div><div class="growth-track" role="progressbar" aria-label="${labels[key][1]}" aria-valuemin="0" aria-valuemax="${goal}" aria-valuenow="${Math.floor(value)}"><i style="width:${Math.min(100,value/goal*100)}%"></i></div></div></div>`).join('')}<p class="growth-hint">${progress.level===2?'Você pode continuar cuidando, brincando e aprendendo.':'As metas são acumuladas desde a adoção. Banhos contam com higiene até 75; refeições com saciedade até 60.'}</p><button class="primary growth-done">Continuar cuidando</button></section>`;
 document.body.append(el);const previous=document.activeElement;
 function close(){document.removeEventListener('keydown',keyboard);el.remove();onClose?.();previous?.isConnected&&previous.focus();}
 function keyboard(e){if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const buttons=[...el.querySelectorAll('button')],first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
 el.querySelector('.close').onclick=close;el.querySelector('.growth-done').onclick=close;el.onclick=e=>{if(e.target===el)close();};document.addEventListener('keydown',keyboard);el.querySelector('.close').focus();
}
