import {petDrawing} from './pets.js';
import '@fontsource/noto-emoji/400.css';
import './style.css';
import {families,species,activeSpecies,palettes,attrs,fresh,valid,tick,care,reward,stage,randomSpecies,shop,buy} from './engine.js';
const root=document.querySelector('#app'),key='petverso-v1';let scene='living',bathStep=0,bathProgress=0,strokeDistance=0;let pet=null,page='home',family='all',message='',activity='idle',game=null,cleanup=()=>{},surprise=false,pendingSpecies=null,pendingColor=0;
try{const s=JSON.parse(localStorage.getItem(key));if(valid(s)){pet=tick(s);if(pet.sleeping)scene='bedroom';}}catch{}
function save(){try{localStorage.setItem(key,JSON.stringify(pet));}catch{message='Não foi possível salvar neste dispositivo.';}}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function icon(name){const paths={coin:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18M12 7v10M9 9h5M9 15h5',feed:'M12 7c-8-6-12 5-7 11 4 5 5 0 7 0s3 5 7-1c4-7 0-14-7-10M12 7q0-6 5-5',pet:'M12 20C-7 9 5-2 12 7c7-9 19 2 0 13',bath:'M9 7a4 4 0 1 0 0 8 4 4 0 0 0 0-8M18 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6M18 16a3 3 0 1 0 0 6 3 3 0 0 0 0-6',sleep:'M19 16A9 9 0 0 1 8 3a9 9 0 1 0 11 13',medicine:'M5 5a5 5 0 0 1 7 0l7 7a5 5 0 0 1-7 7L5 12a5 5 0 0 1 0-7M8 8l8 8',bed:'M3 19V6M21 19V10M3 15h18M3 10h18M7 7h6v3H7z',plant:'M7 15h10l-2 7H9zM12 15V6M12 10Q2 10 5 3q9 0 7 7M12 11Q21 12 21 5q-9-2-9 6',box:'M3 7l9-4 9 4v13H3zM3 7h18M12 7v13',paw:'M6 9a2 2 0 1 0 0 4 2 2 0 0 0 0-4M10 3a2 2 0 1 0 0 4 2 2 0 0 0 0-4M17 4a2 2 0 1 0 0 4 2 2 0 0 0 0-4M20 10a2 2 0 1 0 0 4 2 2 0 0 0 0-4M7 20q-2-6 5-8 7 2 5 8q-5-3-10 0',star:'M12 2l3 7 7 1-5 5 1 7-6-4-6 4 1-7-5-5 7-1z',cloud:'M6 18a5 5 0 0 1-1-10 7 7 0 0 1 13-1 5 5 0 0 1 0 11z',leaf:'M4 20Q0 5 21 3q0 19-17 17M4 20L17 7',ball:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18M8 3q12 8 1 18M3 9q7 11 18 0',rocket:'M7 17Q3 6 20 3q1 17-10 15M8 10L3 12l1 6 5-1M15 17l-1 5-5-1M4 20l-2 2',carrot:'M8 8l8-1-9 15zM14 7l2-5M15 7l6-2',berry:'M5 8q7-4 14 0l-2 11q-5 5-10 0zM8 8l-3-4 7 2 6-2-2 4M9 12h1M14 13h1M11 17h1',clean:'M10 3l5 10M7 12l7-2 6 9-12 3-1-10M10 15l2 6M14 14l2 6',castle:'M3 22V6h4V3h4v3h3V3h4v3h3v16M9 22v-6h6v6'};const aliases={'bed-cloud':'cloud','bed-leaf':'leaf','bed-moon':'sleep',rug:'star',lamp:'star',pets:'paw',exoticos:'leaf',selva:'leaf',dinos:'paw',sombrios:'sleep',memory:'box',sequence:'star',food:'feed',runner:'paw',puzzle:'box',hide:'box'};return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[aliases[name]||name]||paths.star}" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`;}
function mood(){return pet?.sleeping?'sleep':pet?.ill?'sick':pet?.stats.energy<25?'sleepy':pet?.stats.joy>=75?'happy':pet?.stats.joy>=40?'bored':'sad';}
function face(kind){const mouth={happy:'M7 13q5 8 10 0z',bored:'M8 16h8',sad:'M7 17q5-7 10 0',sick:'M8 16h7',sleepy:'M10 14q5-2 5 3t-5 0z',sleep:'M10 14q5-2 5 3t-5 0z'}[kind];return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="10" fill="none" stroke="currentColor" stroke-width="1.6"/><path d="${['sleep','sleepy'].includes(kind)?'M6 9q2 3 4 0M14 9q2 3 4 0':'M8 8v2M16 8v2'}M${kind==='sick'?'17 13l4 7':'12 3'}" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><path d="${mouth}" fill="${kind==='happy'?'white':'none'}" stroke="currentColor" stroke-width="1.6"/></svg>`;}
function drawing(s,mode='idle'){s={...s,palette:s.palette||((pet&&s.id===pet.species)?palettes[s.id]?.find(c=>c.id===pet.color):null),dirty:pet&&s.id===pet.species&&pet.stats.hygiene<60};return petDrawing(s,mode==='idle'&&pet&&s.id===pet.species?mood():mode);}
function render(){
 const s=pet?species.find(x=>x.id===pet.species):null;
 root.innerHTML=`<header><a class="brand" href="#">✦ PetVerso<span>um pequeno mundo, uma grande amizade</span></a>${pet?`<div class="wallet">${icon('coin')} ${pet.coins}</div>`:''}</header><main>${!pet?adoption():pet.dead?memorial():page==='shop'?store():page==='games'?games():home(s)}</main>${pet&&!pet.dead?`<nav>${[['home','⌂','Meu pet'],['games','▶','Brincar'],['shop','✧','Lojinha']].map(([p,i,n])=>`<button data-page="${p}" class="${page===p?'active':''}">${i}<span>${n}</span></button>`).join('')}</nav>`:''}<div role="status" class="toast ${message?'show':''}">${esc(message)}</div>`;
 root.querySelector('.brand').onclick=e=>{e.preventDefault();if(pet){page='home';render();}};
 root.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render();window.scrollTo(0,0);});
 root.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>{family=b.dataset.family;render();});
 root.querySelectorAll('[data-adopt]').forEach(b=>b.onclick=()=>adopt(b.dataset.adopt));
 root.querySelectorAll('[data-need]').forEach(b=>b.onclick=()=>notify(`${attrs[b.dataset.need]}: ${Math.round(pet.stats[b.dataset.need])}/100`));
 root.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{const name=root.querySelector('#adopt-name').value;pendingColor=Number(b.dataset.color);render();root.querySelector('#adopt-name').value=name;});
 root.querySelector('#confirm-adopt')?.addEventListener('click',()=>finishAdoption(pendingSpecies,palettes[pendingSpecies][pendingColor].id,root.querySelector('#adopt-name').value));
 root.querySelector('#cancel-adopt')?.addEventListener('click',()=>{pendingSpecies=null;render();});
 bindScene();root.querySelectorAll('[data-care]').forEach(b=>b.onclick=()=>action(b.dataset.care));
 root.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>start(b.dataset.game));
 root.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{pet=buy(tick(pet),b.dataset.buy);save();render();});
 root.querySelector('#rename')?.addEventListener('click',()=>{const n=prompt('Qual será o nome do seu pet?',pet.name);if(n?.trim()){pet.name=n.trim().slice(0,24);save();render();}});
 root.querySelector('#newpet')?.addEventListener('click',()=>{if(confirm('Iniciar uma nova adoção? Isso apaga o pet, as moedas e os móveis atuais.')){pet=null;save();render();}});
}
function adoption(){if(pendingSpecies){const s=species.find(s=>s.id===pendingSpecies);return `<h1>${s.name}</h1><div class="color-preview">${drawing({...s,palette:palettes[s.id][pendingColor]})}</div><div class="color-options">${palettes[s.id].map((c,i)=>`<button data-color="${i}" class="${pendingColor===i?'selected':''}" aria-label="${c.name}" style="--swatch:${c.color}"><span></span>${c.name}</button>`).join('')}</div><label class="pet-name-label">Nome <input id="adopt-name" maxlength="24" value="${s.name}"></label><button class="primary" id="confirm-adopt">Adotar</button><button id="cancel-adopt">Voltar</button>`;}return `<section class="intro"><p class="eyebrow">BEM-VINDO AO SEU UNIVERSO</p><h1>Uma amizade<br>que cresce com você.</h1><p>Pets, exóticos, selva, dinos e sombrios simpáticos.<br>Escolha seu companheiro ou deixe o ovo surpreender.</p><p class="adoption-warning">Cuidados contam mesmo com o app fechado: necessidades críticas podem causar doença. Três dias doente sem recuperação causam morte definitiva, sem ressurreição.</p><button class="primary" data-adopt="random">✦ Chocar um ovo surpresa</button></section><div class="chips"><button data-family="all" class="${family==='all'?'selected':''}">Todos · ${activeSpecies.length}</button>${families.map(f=>`<button data-family="${f.id}" class="${family===f.id?'selected':''}">${icon(f.id)} ${f.name}</button>`).join('')}</div><section class="catalog">${activeSpecies.filter(s=>family==='all'||s.family===family).map(s=>`<button class="pet-card" data-adopt="${s.id}">${drawing(s)}<strong>${s.name}</strong><small>${families.find(f=>f.id===s.family).name}</small></button>`).join('')}</section>`;}
function finishAdoption(id,color,name){pet=fresh(id,name||species.find(s=>s.id===id).name);if(color)pet.color=color;pendingSpecies=null;scene='living';save();render();window.scrollTo(0,0);if(surprise)notify(`O ovo revelou: ${pet.name}!`);}
function adopt(id){surprise=id==='random';const chosen=surprise?randomSpecies():id;if(!surprise&&palettes[chosen]){pendingSpecies=chosen;pendingColor=0;render();window.scrollTo(0,0);return;}const options=palettes[chosen];finishAdoption(chosen,options?.[Math.floor(Math.random()*options.length)]?.id);}

function memorial(){return `<section class="memorial"><div class="grave">R.I.P.<span>✦</span></div><h1>${esc(pet.name)}</h1><p>Uma amizade que ficou na memória.</p><p class="muted">O pet ficou doente por três dias sem se recuperar.<br>Não há ressurreição. Uma nova adoção começa uma nova história.</p><button id="newpet" class="primary">Adotar um novo companheiro</button></section>`;}
function home(s){const f=families.find(f=>f.id===s.family),bed=shop.find(i=>i.id===pet.equipped?.bed),decor=shop.find(i=>i.id===pet.equipped?.decor),toy=shop.find(i=>i.id===pet.equipped?.toy),rug=shop.find(i=>i.id===pet.equipped?.rug);return `<div class="title-row"><div><p class="eyebrow">${icon(f.id)} ${f.name} · ${stage(pet)}</p><h1>${esc(pet.name)} <button id="rename" class="edit" aria-label="Mudar nome">✎</button></h1></div><span class="pill">${pet.personality}</span></div><div class="room-tabs">${[['living','Sala'],['bathroom','Banheiro'],['bedroom','Quarto']].map(([id,label])=>`<button data-scene="${id}" class="${scene===id?'selected':''}">${label}</button>`).join('')}</div>${room(s,bed,decor,toy,rug)}${pet.ill?`<p class="notice">⚠ Doente há ${Math.floor(pet.illnessHours)} horas. Restam ${Math.ceil(72-pet.illnessHours)} horas para recuperar saúde e necessidades. Morte definitiva se completar três dias doente.</p>`:''}<section class="stats" aria-label="Necessidades do pet">${Object.entries(attrs).map(([k,n])=>{const value=Math.round(pet.stats[k]),level=value>=75?'good':value>=50?'fair':value>=25?'low':'critical',symbol={food:'feed',joy:'pet',energy:'sleep',hygiene:'bath',health:'medicine',intelligence:'star'}[k];return `<button class="need ${level}" data-need="${k}" aria-label="${n}: ${value} de 100" title="${n}">${k==='joy'?face(pet.stats.joy>=75?'happy':pet.stats.joy>=40?'bored':'sad'):k==='health'?face(pet.ill||pet.stats.health<30?'sick':'happy'):k==='energy'?face('sleepy'):icon(symbol)}<span class="need-track"><span style="width:${value}%"></span></span></button>`;}).join('')}</section>${!activeSpecies.some(x=>x.id===pet.species)?'<p class="notice">Este é um pet da versão antiga. Os novos pets têm desenhos próprios; seu progresso antigo foi preservado.</p>':''}<section class="actions">${[['feed','🍎','Alimentar','5 moedas'],['pet','💛','Carinho','Grátis'],['bath','🫧','Banho','Grátis'],['sleep','🌙',pet.sleeping?'Acordar':'Dormir','Descanso'],['medicine','💊','Remédio','12 moedas'],['clean','🧹','Limpar','Grátis']].map(([a,i,n,c])=>`<button data-care="${a}" aria-label="${n}" title="${n}" ${pet.sleeping&&!['sleep','clean'].includes(a)?'disabled':''}><span>${icon(a)}</span><small>${a==='feed'?`5 ${icon('coin')}`:a==='medicine'?`12 ${icon('coin')}`:''}</small></button>`).join('')}</section><details><summary>Ajuda para cuidar</summary><p>Gosta de ${s.food} e ${s.toy}.</p><p>Cuide e brinque para evoluir: jovem aos 40 pontos e adulto aos 120. Progresso: ${pet.xp}. O sono é flexível. Necessidades críticas por 12 horas ou saúde muito baixa causam doença. Três dias seguidos doente sem recuperar saúde e necessidades causam morte definitiva, sem ressurreição. O tempo offline conta integralmente. Este protótipo ainda não envia notificações.</p><button id="newpet">Nova adoção</button></details>`;}
function poop(i){return `<button class="poop poop-${i}" data-poop aria-label="Recolher necessidade"><svg viewBox="0 0 60 60"><path d="M30 5q14 12 1 17c20-1 25 15 9 19 24 3 20 15-10 15S-14 45 8 41C-4 28 15 18 23 21q-1-10 7-16" fill="#9b5e35" stroke="#7c4526" stroke-width="2"/></svg></button>`;}
function room(s,bed,decor,toy,rug){const sleeping=pet.sleeping&&scene==='bedroom',bath=scene==='bathroom';return `<section class="room world ${scene} ${sleeping?'night':''}"><div class="wall-pattern"></div><div class="scenery-window"><div class="landscape"><i></i><i></i><span>${sleeping?'☾':'☀'}</span></div><div class="window-frame"></div></div><div class="floor"></div>${scene==='living'?Array.from({length:pet.floorDirt??pet.waste??0},(_,i)=>`<div class="floor-dirt dirt-${i}" aria-label="Chão sujo"></div>`).join(''):''}${bath?'<div class="bath-shelf"><svg viewBox="0 0 40 60" width="35" height="50"><path d="M15 5h17v5H23v8H15z" fill="#f6be55"/><rect x="8" y="17" width="24" height="38" rx="7" fill="#7fd8cc"/><path d="M13 30h14v13H13z" fill="#fff4dc"/></svg></div><div class="shower"></div>':''}${scene==='bedroom'?`<div class="sleep-bed ${bed?.id||'basic'}"><div class="pillow"></div><div class="blanket"></div></div><div class="bedside-lamp"></div>`:''}${scene==='living'?`<div class="world-decor">${decor?icon(decor.id):''}</div><div class="play-rug ${rug?'rainbow':''}"></div><div class="world-toy">${toy?icon(toy.id):''}</div>`:''}<div class="pet-stage ${bath?'in-tub':sleeping?'in-bed':'roaming'} ${pet.sleeping&&!sleeping?'resting-away':''}" id="touch-pet" tabindex="0" role="button" aria-label="Faça carinho passando o dedo sobre o pet">${drawing(s,sleeping?'sleep':activity)}<div class="hearts"></div>${bath?`<div class="foam ${bathStep===1?'soapy':''}"></div><div class="water ${[0,2].includes(bathStep)?'on':''}"></div>`:''}</div>${bath?`<div class="tub"><div class="tub-rim"></div><div class="bath-paws" style="--paw-color:${pet.species==='selva-4'?'#353d49':palettes[s.id]?.find(c=>c.id===pet.color)?.color||s.color}"><i></i><i></i></div><div class="bath-surface"></div><span>✦</span><i></i><i></i></div>`:''}${scene==='living'?Array.from({length:pet.waste??0},(_,i)=>poop(i)).join(''):''}<span class="room-caption">${bath?['Passe o chuveirinho para molhar.','Esfregue o sabonete para criar espuma.','Passe a água para enxaguar.','Passe a toalha para secar.','Banho completo!'][bathStep]:sleeping?'Dormindo na caminha. Zzz…':pet.sleeping?'Seu pet está dormindo no quarto.':pet.ill?'Preciso de cuidados para ficar bem.':'Passe o dedo em mim para fazer carinho 💛'}</span></section>${bath?`<div class="bath-controls"><p>${['Molhar','Ensaboar','Enxaguar','Secar','Prontinho!'][bathStep]} · ${Math.round(bathProgress)}%</p><progress max="100" value="${bathProgress}"></progress><button id="bath-assist" ${bathStep>=4?'disabled':''}>${['Usar chuveiro','Passar sabonete','Enxaguar','Usar toalha','Limpo!'][bathStep]}</button><small>Arraste sobre o pet. O botão também permite completar cada etapa.</small></div>`:''}`;}
function bindScene(){root.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{scene=b.dataset.scene;render();});root.querySelectorAll('[data-poop]').forEach(b=>b.onclick=()=>{pet=care(tick(pet),'pickup');save();render();});const target=root.querySelector('#touch-pet');if(!target)return;let dragging=false,last=null,total=0,lastReward=0;const react=()=>{target.classList.add('petted');setTimeout(()=>target.classList.remove('petted'),1000);};function scrub(amount){if(scene==='bathroom'){if(pet.sleeping||pet.dead||bathStep>=4)return;bathProgress=Math.min(100,bathProgress+amount);const progress=root.querySelector('.bath-controls progress');if(progress)progress.value=bathProgress;root.querySelector('.bath-controls p').textContent=`${['Molhar','Ensaboar','Enxaguar','Secar'][bathStep]} · ${Math.round(bathProgress)}%`;if(bathProgress>=100){bathStep++;bathProgress=0;if(bathStep>=4){pet=care(tick(pet),'bath');save();notify('Banho completo! Seu pet está limpinho.');}render();}}else{if(pet.sleeping||pet.dead)return;total+=amount;react();if(total>=60&&Date.now()-lastReward>1500){lastReward=Date.now();total=0;pet=care(tick(pet),'pet');save();}}}
 target.onpointerdown=e=>{dragging=true;last={x:e.clientX,y:e.clientY};target.setPointerCapture(e.pointerId);target.classList.add('being-touched');};target.onpointermove=e=>{if(!dragging)return;const distance=Math.hypot(e.clientX-last.x,e.clientY-last.y);last={x:e.clientX,y:e.clientY};if(distance>2)scrub(Math.min(12,distance*.35));};target.onpointerup=target.onpointercancel=()=>{dragging=false;last=null;target.classList.remove('being-touched');if(scene!=='bathroom')render();};target.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();scrub(25);}};root.querySelector('#bath-assist')?.addEventListener('click',()=>scrub(25));}
function action(a){pet=tick(pet);if(a==='bath'){if(pet.sleeping)return notify('Acorde seu pet para tomar banho.');scene='bathroom';bathStep=0;bathProgress=0;render();return;}if(a==='sleep')scene=pet.sleeping?'living':'bedroom';if(a==='feed'&&pet.coins<5)return notify('Faltam moedas. Brinque para ganhar mais!');if(a==='medicine'&&(pet.coins<12||pet.stats.health>=90))return notify(pet.stats.health>=90?'Está saudável! Remédio só quando precisar.':'Você precisa de 12 moedas.');pet=care(pet,a);save();activity=a==='feed'?'eat':a==='bath'?'bath':a==='pet'?'happy':'idle';render();setTimeout(()=>{activity='idle';if(page==='home'&&!game)render();},1800);}
const mini=[['memory','🃏','Memória','Encontre os pares.','Inteligência'],['sequence','🎵','Repita a sequência','Observe as cores e repita.','Inteligência'],['food','🍓','Caça aos petiscos','Pegue os bons; evite os estragados.','Felicidade'],['runner','🏃','Corrida','O cenário anda. Toque para pular.','Felicidade'],['puzzle','🧩','Quebra-cabeça','Deslize as peças para montar.','Inteligência'],['hide','🙈','Esconde-esconde','Observe e encontre seu pet.','Inteligência']];
function games(){return `<p class="eyebrow">HORA DE BRINCAR</p><h1>Pequenos desafios.<br>Grandes conquistas.</h1><p class="muted">3 a 13 moedas por partida · custa 8 de energia.<br>Os jogos de raciocínio também aumentam a inteligência.</p>${pet.sleeping||pet.stats.energy<10?'<p class="notice">Seu pet precisa acordar ou descansar antes de brincar.</p>':''}<section class="game-grid">${mini.map(([id,i,n,d,b])=>`<button class="game-card" data-game="${id}" ${pet.sleeping||pet.stats.energy<10?'disabled':''}><span>${icon(id)}</span><strong>${n}</strong><p>${d}</p><small>${b}</small></button>`).join('')}</section>`;}
function store(){return `<p class="eyebrow">CONSTRUA SEU CANTINHO</p><h1>Coisinhas que<br>fazem um lar.</h1><p class="muted">Uma partida rende até 13 moedas. Economize para seus favoritos.<br>A cama básica é grátis; os modelos especiais são conquistas.</p><section class="shop-grid">${shop.map(i=>{const owned=pet.inventory?.includes(i.id),equipped=pet.equipped?.[i.slot]===i.id;return `<article class="shop-card"><span>${icon(i.id)}</span><h3>${i.name}</h3><b>🪙 ${i.price}</b><button data-buy="${i.id}" ${equipped||!owned&&pet.coins<i.price?'disabled':''}>${equipped?'No quarto':owned?'Usar':'Comprar'}</button></article>`;}).join('')}</section>`;}
function notify(text){message=text;const el=document.querySelector('.toast');if(el){el.textContent=text;el.classList.add('show');}setTimeout(()=>{message='';document.querySelector('.toast')?.classList.remove('show');},3500);}
function modal(title,content){const el=document.createElement('div');el.className='overlay';el.innerHTML=`<section class="dialog" role="dialog" aria-modal="true" aria-label="${title}"><button class="close" aria-label="Fechar">×</button><p class="eyebrow">BRINCANDO JUNTOS</p><h2>${title}</h2><div id="play">${content}</div></section>`;document.body.append(el);el.querySelector('.close').onclick=()=>{cleanup();game=null;el.remove();render();};el.querySelector('.close').focus();return el.querySelector('#play');}
function finish(score,smart){if(!game||game==='finished')return;cleanup();const p=pet.coins;pet=reward(tick(pet),score,smart);save();const wallet=document.querySelector('.wallet');if(wallet)wallet.innerHTML=`${icon('coin')} ${pet.coins}<small>+${pet.coins-p}</small>`;const area=document.querySelector('#play');area.innerHTML=`<div class="result">✦<h2>Boa brincadeira!</h2><p>${Math.round(score)} pontos · +${pet.coins-p} moedas</p><p>${smart?'Seu pet aprendeu um pouco mais.':'Seu pet ficou mais feliz.'}</p><button class="primary" id="done">Voltar para meu pet</button></div>`;area.querySelector('#done').onclick=()=>{document.querySelector('.overlay').remove();game=null;page='home';render();};game='finished';}
function start(id){pet=tick(pet);if(pet.sleeping||pet.stats.energy<10)return notify('Descanse primeiro.');cleanup=()=>{};game=id;const area=modal(mini.find(m=>m[0]===id)[2],'');({memory,sequence,food,runner,puzzle,hide}[id])(area);}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function memory(a){const cards=shuffle(['feed','sleep','leaf','paw','star','pet','feed','sleep','leaf','paw','star','pet']);let opened=[],found=new Set(),turns=0,locked=false;const timeouts=[];cleanup=()=>timeouts.forEach(clearTimeout);a.innerHTML='<p>Encontre os seis pares.</p><div class="memory-board">'+cards.map((_,i)=>`<button data-card="${i}" aria-label="Carta ${i+1}">?</button>`).join('')+'</div>';a.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{const i=+b.dataset.card;if(locked||found.has(i)||opened.includes(i))return;b.innerHTML=icon(cards[i]);opened.push(i);if(opened.length===2){turns++;const [x,y]=opened;if(cards[x]===cards[y]){found.add(x);found.add(y);a.querySelector(`[data-card="${x}"]`).classList.add('matched');a.querySelector(`[data-card="${y}"]`).classList.add('matched');opened=[];if(found.size===cards.length)finish(Math.max(20,100-(turns-6)*5),true);}else{locked=true;timeouts.push(setTimeout(()=>{a.querySelectorAll('[data-card]').forEach(c=>{if(!found.has(+c.dataset.card))c.textContent='?';});opened=[];locked=false;},650));}}});}
function sequence(a){let seq=[],index=0,showing=false,level=0,timers=[];const colors=['#f25587','#ffc536','#32cbb0','#9261ec'];cleanup=()=>timers.forEach(clearTimeout);a.innerHTML='<p id="hint">Observe a sequência.</p><div class="sequence-board">'+colors.map((c,i)=>`<button data-color="${i}" style="background:${c}" aria-label="Cor ${i+1}">${['●','▲','■','★'][i]}</button>`).join('')+'</div>';const buttons=[...a.querySelectorAll('[data-color]')],hint=a.querySelector('#hint');function next(){level++;seq.push(Math.floor(Math.random()*4));index=0;showing=true;hint.textContent=`Observe · nível ${level}/6`;seq.forEach((v,k)=>{timers.push(setTimeout(()=>buttons[v].classList.add('flash'),700+k*650));timers.push(setTimeout(()=>buttons[v].classList.remove('flash'),1100+k*650));});timers.push(setTimeout(()=>{showing=false;hint.textContent='Sua vez!';},700+seq.length*650));}buttons.forEach((b,i)=>b.onclick=()=>{if(showing)return;if(i!==seq[index])return finish((level-1)*16,true);index++;if(index===seq.length){showing=true;if(level===6)finish(100,true);else timers.push(setTimeout(next,500));}});next();}
function food(a){let points=0,left=30;const timers=[];cleanup=()=>timers.forEach(clearInterval);a.innerHTML='<p id="score">30 segundos · toque nos petiscos frescos.</p><div class="food-field"></div>';const field=a.querySelector('.food-field');function spawn(){field.innerHTML='';for(let i=0;i<5;i++){const bad=Math.random()<.3,b=document.createElement('button');b.innerHTML=bad?face('sick'):icon(['feed','berry','carrot'][Math.floor(Math.random()*3)]);b.className=bad?'spoiled':'fresh';b.style.left=`${5+Math.random()*75}%`;b.style.top=`${5+Math.random()*70}%`;b.setAttribute('aria-label',bad?'Comida estragada':'Petisco fresco');b.onclick=()=>{points=Math.max(0,points+(bad?-10:5));b.remove();};field.append(b);}}spawn();timers.push(setInterval(spawn,1600));timers.push(setInterval(()=>{left--;a.querySelector('#score').textContent=`${left}s · ${points} pontos`;if(!left)finish(Math.min(100,points),false);},1000));}
function runner(a){a.innerHTML='<p>Cenário automático · toque no jogo para pular.<br>30 segundos, três tentativas.</p><canvas width="600" height="260" aria-label="Corrida: toque ou pressione espaço para pular" tabindex="0"></canvas><p id="score"></p>';const c=a.querySelector('canvas'),ctx=c.getContext('2d'),s=species.find(s=>s.id===pet.species);const sprite=new Image();sprite.src='data:image/svg+xml,'+encodeURIComponent(drawing(s).replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" '));let y=0,vy=0,obstacles=[],last=performance.now(),elapsed=0,next=1,lives=3,passed=0,raf;const jump=()=>{if(y===0)vy=460;};const keypress=e=>{if(e.code==='Space'){e.preventDefault();jump();}};c.onpointerdown=jump;document.addEventListener('keydown',keypress);cleanup=()=>{cancelAnimationFrame(raf);document.removeEventListener('keydown',keypress);};function frame(now){let dt=Math.min(.035,(now-last)/1000);last=now;elapsed+=dt;next-=dt;if(next<=0){obstacles.push({x:620,hit:false});next=1.3+Math.random()*.8;}vy-=1100*dt;y=Math.max(0,y+vy*dt);if(!y)vy=0;const sky=ctx.createLinearGradient(0,0,0,260);sky.addColorStop(0,'#55cdf3');sky.addColorStop(1,'#d2fbff');ctx.fillStyle=sky;ctx.fillRect(0,0,600,260);ctx.fillStyle='#70cd5d';ctx.fillRect(0,215,600,45);for(let i=0;i<7;i++){ctx.fillStyle=i%2?'#9ee86c':'#56be80';ctx.beginPath();ctx.arc((i*110-elapsed*35%110),185,30,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#ffe57b';ctx.beginPath();ctx.arc(510,48,25,0,Math.PI*2);ctx.fill();if(sprite.complete&&sprite.naturalWidth)ctx.drawImage(sprite,57,143-y,78,78);else{ctx.fillStyle=s.color;ctx.beginPath();ctx.ellipse(95,190-y,25,25,0,0,Math.PI*2);ctx.fill();}obstacles.forEach(o=>{o.x-=220*dt;ctx.fillStyle=o.hit?'#e95667':'#aa6ce6';ctx.fillRect(o.x,185,23,30);ctx.fillStyle='#edcaff';ctx.fillRect(o.x+3,188,17,5);if(!o.hit&&o.x<120&&o.x+23>70&&y<55){o.hit=true;lives--;}if(o.x<45&&!o.counted){o.counted=true;if(!o.hit)passed++;}});obstacles=obstacles.filter(o=>o.x>-30);a.querySelector('#score').textContent=`${Math.ceil(30-elapsed)}s · ${'♥'.repeat(Math.max(0,lives))} · ${passed} obstáculos`;if(lives<=0||elapsed>=30)return finish(Math.min(100,passed*8),false);raf=requestAnimationFrame(frame);}c.focus();raf=requestAnimationFrame(frame);}
function puzzle(a){const image='data:image/svg+xml,'+encodeURIComponent(drawing(species.find(s=>s.id===pet.species)).replace('<svg ', '<svg xmlns="http://www.w3.org/2000/svg" '));let tiles=[1,2,3,4,5,6,7,8,0],moves=0;const adjacent=z=>[z%3>0?z-1:-1,z%3<2?z+1:-1,z>=3?z-3:-1,z<6?z+3:-1].filter(i=>i>=0);for(let k=0;k<60;k++){const z=tiles.indexOf(0),list=adjacent(z),i=list[Math.floor(Math.random()*list.length)];[tiles[z],tiles[i]]=[tiles[i],tiles[z]];}if(tiles.every((v,i)=>v===(i+1)%9)){[tiles[7],tiles[8]]=[tiles[8],tiles[7]];}function draw(){a.innerHTML='<p>Monte a imagem do seu pet. Os números ajudam: ordem de 1 a 8. Toque numa peça vizinha do espaço vazio.</p><div class="puzzle-board">'+tiles.map((v,i)=>`<button data-tile="${i}" style="background-image:url('${v?image:''}');background-size:300% 300%;background-position:${((v-1)%3)*50}% ${Math.floor((v-1)/3)*50}%" ${!v?'disabled':''}>${v||''}</button>`).join('')+`</div><p>${moves} movimentos</p>`;a.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{const i=+b.dataset.tile,z=tiles.indexOf(0);if(!adjacent(z).includes(i))return;[tiles[z],tiles[i]]=[tiles[i],tiles[z]];moves++;if(tiles.every((v,i)=>v===(i+1)%9))finish(Math.max(20,100-Math.max(0,moves-25)),true);else draw();});}draw();}
function hide(a){let round=0,points=0,hidden=0,ready=false,timer;cleanup=()=>clearTimeout(timer);function next(){round++;hidden=Math.floor(Math.random()*4);ready=false;a.innerHTML=`<p id="hint">Observe onde estou · ${round}/5</p><div class="hide-board">${[0,1,2,3].map(i=>`<button data-hide="${i}" aria-label="Esconderijo ${i+1}" data-revealed="${i===hidden}">${icon(i===hidden?'paw':'box')}</button>`).join('')}</div>`;timer=setTimeout(()=>{a.querySelectorAll('[data-hide]').forEach(b=>{b.innerHTML=icon('box');delete b.dataset.revealed;});a.querySelector('#hint').textContent='Em qual caixa eu estava?';ready=true;},Math.max(500,1600-round*180));a.querySelectorAll('[data-hide]').forEach(b=>b.onclick=()=>{if(!ready)return;ready=false;if(+b.dataset.hide===hidden)points+=20;b.innerHTML=+b.dataset.hide===hidden?icon('pet'):face('sad');timer=setTimeout(()=>round===5?finish(points,true):next(),600);});}next();}
setInterval(()=>{if(pet&&!game){pet=tick(pet);save();if(page==='home'&&activity==='idle')render();}},60000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&pet){pet=tick(pet);save();if(game&&game!=='finished'){cleanup();document.querySelector('.overlay')?.remove();game=null;notify('A brincadeira foi pausada. Seu pet continua salvo.');}render();}});
render();
