import {colorfulIcon} from './icons.js';
const star='<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M24 5l5.5 12 13 1.5-9.5 9 2.5 13L24 34l-11.5 6.5 2.5-13-9.5-9L18.5 17Z" fill="#ffe28b" stroke="#c49a56" stroke-width="2.5" stroke-linejoin="round"/><path d="M20 15l-3 7-7 1" stroke="#fff9dc" stroke-width="2.5" fill="none" stroke-linecap="round"/></svg>';
export function skillBadge(p,scene,remaining=0){
 const required=scene==='playground'?75:50,locked=!['sombrios-frankie','sombrios-6'].includes(p.species)&&p.stats.intelligence<required;
 return `<button class="skill-badge ${locked?'skill-locked':remaining?'skill-cooldown':''}" aria-disabled="${locked||remaining>0}" aria-label="${locked?`Habilidade bloqueada: ${required} de inteligência`:remaining?`Aguarde ${remaining} segundos`:'Usar habilidade'}" title="Habilidade">${star}${locked?'<span class="skill-lock">🔒</span>':remaining?`<span class="skill-seconds">${remaining}</span>`:''}</button>`;
}
export function openSkillProgress(p,scene,{required,label}={}){
 const current=Math.floor(p.stats.intelligence),need=required??(scene==='playground'?75:50),el=document.createElement('div');el.className='overlay skills-overlay';
 el.innerHTML=`<section class="dialog skills-dialog" role="dialog" aria-modal="true" aria-labelledby="skills-title"><button class="close" aria-label="Fechar">×</button><div class="skills-brain">${colorfulIcon('brain')}</div><h2 id="skills-title">Minhas habilidades</h2><p>${label||(scene==='playground'?'Brinquedo do Parquinho':'Habilidade na Sala')}</p><strong class="skills-number">${current} / ${need}</strong><div class="growth-track"><i style="width:${Math.min(100,current/need*100)}%"></i></div><ul>${[[25,'Seguir seu toque'],[50,'Truque da espécie'],[75,'Brincar no Parquinho']].map(([n,label])=>`<li><span>${label}</span><b>${current>=n?'✓':n+' 🧠'}</b></li>`).join('')}</ul><button class="primary skills-close">Continuar cuidando</button></section>`;
 document.body.append(el);const previous=document.activeElement;function close(){document.removeEventListener('keydown',key);el.remove();previous?.isConnected&&previous.focus();}function key(e){if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const list=[...el.querySelectorAll('button')],first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
 el.querySelector('.close').onclick=close;el.querySelector('.skills-close').onclick=close;el.onclick=e=>{if(e.target===el)close();};document.addEventListener('keydown',key);el.querySelector('.close').focus();
}
